---
- name: Install Nginx
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Create SSL folder
  file:
    path: /etc/nginx/ssl
    state: directory
    mode: 0755

- name: Generate self-signed certificate
  shell: |
    openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
    -keyout /etc/nginx/ssl/nginx.key \
    -out /etc/nginx/ssl/nginx.crt \
    -subj "/CN=localhost"
  args:
    creates: /etc/nginx/ssl/nginx.crt

- name: Create config file
  template: 
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/myapp.conf  
  notify: Reload Nginx

- name: Enable site
  file:
    src: /etc/nginx/sites-available/myapp.conf
    dest: /etc/nginx/sites-enabled/myapp.conf
    state: link

- name: Secure private key
  file:
    path: /etc/nginx/ssl/nginx.key
    mode: '0600'

- name: Remove default nginx config
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: Reload Nginx