apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-jaeger
spec:
  selector:
    app: {{ .Release.Name }}-jaeger
  ports:
    - name: ui
      port: {{ .Values.jaeger.uiPort }}
      targetPort: {{ .Values.jaeger.uiPort }}
    - name: otlp
      port: {{ .Values.jaeger.otlpPort }}
      targetPort: {{ .Values.jaeger.otlpPort }}